In [1]:
import numpy as np  # import the numpy library for numerical computations
import pandas as pd  # import the pandas library for data manipulation

In [2]:
data = pd.read_csv("Gluecose-Level-Age.csv")  # load the dataset from a CSV file

In [3]:
data  # display the loaded dataset

Age  Gluecose-level
0   43              99
1   21              65
2   25              79
3   42              75
4   57              87
5   59              81

In [4]:
data.shape  # display the shape of the dataset (number of rows and columns)

(6, 2)

In [5]:
x=data['Age']  # extract the age column from the dataset

In [6]:
y=data['Gluecose-level']  # extract the glucose level column from the dataset

In [7]:
from sklearn.model_selection import train_test_split  # import the train_test_split function for splitting the dataset

In [8]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=1)  # split the dataset into training and testing sets

In [9]:
from sklearn.linear_model import LinearRegression  # import the LinearRegression class for creating a linear regression mode

In [10]:
le = LinearRegression()  # create an instance of the LinearRegression class

In [11]:
le.fit(xtrain.values.reshape(-1,1),ytrain)  # fit the training data to the linear regression model

LinearRegression()

In [12]:
le.predict(xtest.values.reshape(-1, 1))  # make predictions on the testing data using the trained mode

array([89.71266735, 90.3800206 ])

In [13]:
le.predict([[55]])  # make a single prediction for a new age value of 55

array([84.70751802])

In [14]:
import pickle  # import the pickle library for saving and loading Python objects

In [16]:
pickle.dump(le, open('glucose_model.pkl', 'wb'))

In [18]:
pipe=pickle.load(open("glucose_model.pkl",'rb'))


In [20]:
pipe.predict([[55]])

array([84.70751802])